biblioteca/biblioteca/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

biblioteca/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('cadastro', views.cadastro, name='cadastro'),
    path('listar', views.listar, name='listar'),
]

biblioteca/core/models.py
from django.db import models

class LivroModel(models.Model):
    titulo = models.CharField('Título', max_length=200)
    editora = models.CharField('Editora', max_length=200)
    autor = models.CharField('Autor', max_length=200)
    isbn = models.IntegerField(null=True)
    num_pag = models.IntegerField(null=True)
    ano = models.IntegerField(null=True)

    def __str__(self):
        return self.titulo

biblioteca/core/forms.py
from django import forms
from django.core.exceptions import ValidationError
from core.models import LivroModel


def validate_titulo(titulo):
    if len(titulo) < 3:
        raise ValidationError('Deve ter pelo menos 3 caracteres')
    
def validate_editora(editora):
    if len(editora) < 3:
        raise ValidationError('Deve ter pelo menos 3 caracteres')
    
def validate_autor(autor):
    if len(autor) < 10:
        raise ValidationError('Deve ter pelo menos 10 caracteres')
    
def validate_isbn(isbn):
    numero_str = str(isbn)
    if len(numero_str) != 13:
        raise ValidationError('Deve ter 13 caracteres')
    
def validate_num_pag(num_pag):
    if num_pag < 1 or  num_pag > 999:
        raise ValidationError('Deve ter de 1 a 3 caracteres')
    

def validate_ano(ano):
    numero_str = str(ano)
    if len(numero_str) != 4:
        raise ValidationError('Deve ter 4 caracteres')
    
    



class LivroForm(forms.ModelForm):

    class Meta:
        model = LivroModel
        fields = ['titulo', 'editora','autor','isbn','num_pag','ano']
        error_messages = {
            'titulo': {
                'required': ("Informe o título do livro."),
            },
            'editora': {
                'required': ("Informe a editora do livro."),
            },
            'autor': {
                'required': ("Informe o autor do livro."),
            },
            'isbn': {
                'required': ("Informe a ISBN do livro."),
            },
            'num_pag': {
                'required': ("Informe o número de páginas do livro."),
            },
            'ano': {
                'required': ("Informe o ano do livro."),
            },

        }

    def clean_titulo(self):
        titulo = self.cleaned_data['titulo']
        validate_titulo(titulo)
        return titulo

    def clean_editora(self):
        editora = self.cleaned_data['editora']
        validate_editora(editora)
        return editora
    
    def clean_autor(self):
        autor = self.cleaned_data['autor']
        validate_autor(autor)
        return autor

    def clean_isbn(self):
        isbn = self.cleaned_data['isbn']
        validate_isbn(isbn)
        return isbn
    
    def clean_num_pag(self):
        num_pag = self.cleaned_data['num_pag']
        validate_num_pag(num_pag)
        return num_pag

    def clean_ano(self):
        ano = self.cleaned_data['ano']
        validate_ano(ano)
        return ano
    
    def clean(self):
        self.cleaned_data = super().clean()
        return self.cleaned_data

biblioteca/core/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from .forms import LivroForm
from .models import LivroModel

def index(request):
    if request.method == 'GET':
        return render(request, "index.html")
    else:
        return HttpResponseRedirect(reverse('core:index'))

def cadastro(request):
    if request.method == 'POST':
        form_livro = LivroForm(request.POST)
        if form_livro.is_valid():
            eleitor = LivroModel.objects.create(**form_livro.cleaned_data)
            return HttpResponseRedirect(reverse('core:index'))
        else:
            contexto = {'formulario_livro': form_livro}
            return render(request, "cadastro.html", contexto)
    else:
        contexto = {'formulario_livro': LivroForm()}
        return render(request, 'cadastro.html', contexto)

def listar(request):
    if request.method == 'POST':
        livro_id = request.POST.get('livro_id', '')
        try:
            livro = LivroModel.objects.get(pk=livro_id)
            contexto = {'livro': livro}
        except ValueError:
            contexto = {}
        return render(request, "detalhes.html", contexto)
    else:
        livros = LivroModel.objects.all()
        contexto = {'livros': livros}
        return render(request, 'listar.html', contexto)

biblioteca/core/templates/cadastro.html
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="author" content="Orlando Saraiva do Nascimento Júnior">
        <link rel="stylesheet" href="{% static '/css/style.css' %}">
        <title>Biblioteca</title>
    </head>
    <body>
        <br>
            <h1> Biblioteca </h1>
            <h2> Cadastro de Livros </h2>
        <br>

        <form action={% url 'core:cadastro' %} novalidate method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h3>
                {{ formulario_livro.titulo.label }} : {{ formulario_livro.titulo }}
            </h3>
            <br>
            <h3>
                {{ formulario_livro.editora.label }}: {{ formulario_livro.editora }}
            </h3>
            <h3>
                {{ formulario_livro.autor.label }} : {{ formulario_livro.autor }}
            </h3>
            <br>
            <h3>
                {{ formulario_livro.isbn.label }} : {{ formulario_livro.isbn }}
            </h3>
            <br>
            <h3>
                {{ formulario_livro.num_pag.label }} : {{ formulario_livro.num_pag }}
            </h3>
            <br>
            <h3>
                {{ formulario_livro.ano.label }} : {{ formulario_livro.ano }}
            </h3>
        
            <br><br>
            <center>
                <input type="submit" value="Cadastrar"/>
            </center>
        </form>
        {% if formulario_livro.errors %}
            {% for field in formulario_livro %}
                {% for error in field.errors %}
                    <strong>{{ error|escape }}</strong><br>
                {% endfor %}
            {% endfor %}
        {% endif %}

        <center>
            <form action={% url 'core:index' %} novalidate method="GET">
                <input type="submit" value="Voltar"/>              
            </form>
        </center>
    </body>

</html>

biblioteca/core/templates/detalhes.html
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="author" content="Orlando Saraiva do Nascimento Júnior">
        <link rel="stylesheet" href="{% static '/css/style.css' %}">
        <title>Biblioteca</title>
    </head>
    <body>
        <br>
            <h1> Biblioteca </h1>
        <br>

        {% if livro %}
            <h2> Detalhes de um livro selecionado </h2>
            <h3>
                Livro :  {{ livro.titulo }}
                <br><br>
                Editora : {{ livro.editora }}
                <br><br>
                Autor :  {{ livro.autor }}
                <br><br>
                ISBN : {{ livro.isbn }}
                <br><br>
                Numero de Páginas : {{ livro.num_pag }}
                <br><br>
                Ano : {{ livro.ano }}
            </h3>
        <br><br>
        {% else %}
            <h2> Nenhum livro cadastrado </h2>      
        {% endif %} 

        <center>
            <form action={% url 'core:listar' %} novalidate method="GET">
                <input type="submit" value="Voltar"/>              
            </form>
        </center>
    </body>

</html>

biblioteca/core/templates/index.html
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="author" content="Orlando Saraiva do Nascimento Júnior">
        <link rel="stylesheet" href="{% static '/css/style.css' %}">
        <title>Biblioteca</title>
    </head>
    <body>
        <br>
            <h1> Biblioteca </h1>
            <h2> Sistema para cadastro de livros </h2>
        <br>
        <form action={% url 'core:cadastro' %} novalidate method="GET">
            <input type="submit" value="Cadastrar"/>              
        </form>
        <br>
        <form action={% url 'core:listar' %} novalidate method="GET">
            <input type="submit" value="Listar"/>              
        </form>
    </body>

</html>

biblioteca/core/templates/listar.html
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="author" content="Orlando Saraiva do Nascimento Júnior">
        <link rel="stylesheet" href="{% static '/css/style.css' %}">
        <title>Biblioteca</title>
    </head>
    <body>
        <br>
            <h1> Biblioteca </h1>
            <h2> Listar os livros cadastrados </h2>
        <br>

        {% if livros %}
            <h3>Livros Cadastrados</h3>
            {% for livro in livros %}
                <form action={% url 'core:listar' %} novalidate method="POST" enctype="multipart/form-data">
                    {% csrf_token %}        
                    Livro: {{ livro }}
                    <input type="hidden" name="livro_id" value={{ livro.pk }}>        
                    <input type="submit" value="Detalhes"/>              
                </form>
            {% endfor %}
        {% else %}
            <h2> Nenhum livro cadastrado </h2>      
        {% endif %} 

        <center>
            <form action={% url 'core:index' %} novalidate method="GET">
                <input type="submit" value="Voltar"/>              
            </form>
        </center>
    </body>

</html>